baseURL = 'https://arpitjn.com/'
languageCode = 'en-us'
title = 'Arpit J | Notes'
theme = ['hugo-embed-pdf-shortcode', 'Typo']

[taxonomies]
tag = 'tags'


[params]
description = 'I (occasionally) write on tech I use, things I do, and stuff I learn.'
# Google analytics code
googleAnalytics = "G-800SX4Q25Q"

# Appearance settings
theme = 'auto'

# Intro on main page, content is markdown
homeIntroTitle = 'Hello 👋, I am Arpit'
homeIntroContent = """
I (occasionally) write on tech I use, things I do, and stuff I learn.
"""

# Collection to display on home
homeCollectionTitle = 'Notes'
homeCollection = 'notes'

# Lists parameters
paginationSize = 5
listSummaries = true
listDateFormat = 'Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/arpitxjain/"

[[params.social]]
name = "medium"
url = "https://arpitjain-23306.medium.com/"

[[params.social]]
name = "github"
url = "https://github.com/osbins"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "notes"
url = "/notes"


# [[params.menu]]
# name = "about"
# url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
